spring:
  application:
    name: shoprider
  datasource:
    url: jdbc:postgresql://localhost:5432/shopridertest
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
server:
  port: 8080
